### ISSUE TITLE
Add programmatic interface for trigger to enable concurrent job execution

### ISSUE THREAD

**Issue by miyamoto-daisuke** [timmolter/Sundial#10]
When we register trigger programmatically (manually), we cannot enable concurrent jbo execution.

**Comment by timmolter** [comment]
Thanks for reporting the issue. I'll look into it.

**Comment by timmolter** [comment]
I added a param for this in one of the `addJob` methods. Please test with the latest snapshot jar.

**Comment by miyamoto-daisuke** [comment]
Thanks!
