### ISSUE TITLE
Support for custom implementation of JobFactory

### ISSUE THREAD

**Issue by lind** [timmolter/Sundial#23]
It would be nice to be able to implement a custom JobFactory to be used instead of [SimpleJobFactory](https://github.com/timmolter/Sundial/blob/51307ab95bbfa8b9e738b24dc6249437f43fbbbc/src/main/java/org/quartz/jobs/SimpleJobFactory.java). The SimpleJobFactory is insansiated in [QuartzScheduler](https://github.com/timmolter/Sundial/blob/51307ab95bbfa8b9e738b24dc6249437f43fbbbc/src/main/java/org/quartz/QuartzScheduler.java) and quite hard to override.
What about:
1. adding a new constructor in QuartzScheduler with a JobFactory
2. adding JobFactory as a parameter to SchedulerFactory.instantiate()
3. and to SchedulerFactory.getScheduler()
4. and finally to SundialJobScheduler.createScheduler()
Or is there an easier way?

**Comment by lind** [comment]
Or as in https://github.com/timmolter/Sundial/pull/24

**Comment by timmolter** [comment]
merged

**Comment by fieldju** [comment]
I see that #24 was merged, but the setter no longer seems to be available in Master.
How does one go about creating jobs that have there dependencies injected now?
