### ISSUE TITLE
Create new release to include enhanced error logging

### ISSUE THREAD

**Issue by msmerc** [timmolter/Sundial#33]
Is there any chance I could persuade you to push out a release that includes: 

https://github.com/timmolter/Sundial/pull/32

Pretty please? :)

**Comment by timmolter** [comment]
Sorry, I'm on vacation and don't have access to the crypto keys I need to push a release to maven central. I will do it though in a week or so.

**Comment by msmerc** [comment]
Ok no worries - many thanks!

**Comment by timmolter** [comment]
done.
