### ISSUE TITLE
Start job by name

### ISSUE THREAD

**Issue by gverhemeldonck** [timmolter/Sundial#34]
Whenever I try to start a job based on the jobName (http://localhost:9083/tasks/startjob?JOB_NAME=MyCronJob&id=123456), it throws an error:

```
ERROR [2017-06-15 12:22:43,440] org.knowm.sundial.SundialJobScheduler: ERROR STARTING JOB!!!
! org.quartz.exceptions.JobPersistenceException: The job (MyCronJob) referenced by the trigger does not exist.
! at org.quartz.core.RAMJobStore.storeTrigger(RAMJobStore.java:249)
...
```

I've tried to register my jobs using annotations, via jobs.xml or via API but the result is always the same: Quartz doesn't know about any jobs. The variable jobsByKey is always empty in org.quartz.core.RAMJobStore.

I'm on dropwizard-sundial 1.1.0.0  (Sundial 2.1.2).

**Comment by timmolter** [comment]
There's a working example here: <https://github.com/timmolter/XDropWizard>
Using the following command works for me: `curl -X POST "http://localhost:9090/admin/tasks/startjob?JOB_NAME=MyJob"`
