### ISSUE TITLE
Jobs.xml not parsing 

### ISSUE THREAD

**Issue by vishnudivakar31** [timmolter/Sundial#37]
I got a sundial scheduler job which should run with the help of jobs.xml. When I start dropwizard application the jobs.xml file get detected but getting some error while parsing the file.

I am trying to use simple trigger and only one job is there in Class: com.listener.Listener. Kindly help me to solve this issue.

I am attaching job.xml and error which was thrown.

[jobs.txt](https://github.com/timmolter/Sundial/files/1286848/jobs.txt)
[error.txt](https://github.com/timmolter/Sundial/files/1286847/error.txt)

**Comment by timmolter** [comment]
The jobs.xml file is valid. I just tested it. It looks like it's not on the classpath in your dropwizard app. 

I would suggest taking a look at <https://github.com/timmolter/XDropWizard>, which is a working example, and see what's wrong on your end.

**Comment by vishnudivakar31** [comment]
Thank you. Let me try according to the sample project you provided.

**Comment by vishnudivakar31** [comment]
Hi,

I tried according to you example and I kept jobs.xml in src/main/resource and added the folder to classpath. And when I running the dropwizard App the jobs.xml file is not getting detected. Please tell me what I am doing wrong.

**Comment by timmolter** [comment]
I'm not sure, but my guess is that it's not really on the classpath. Otherwise it has to work!
